hardware:
  encoders:
    - id: 1
      midi_CC: 104
      midi_port: c4
      longpress: previous_snapshot
      # shortpress: {callback: send_midi_cc, args: {cc: 72}}  # Uncomment to send MIDI CC on button press
    - id: 2
      midi_CC: 71
      longpress: next_snapshot
    - id: 3
      type: VOLUME
